// Color palette (mirrors the original Lip Gloss theme)
export const colors = {
	primary: '#7D56F4',
	secondary: '#00E5FF',
	accent: '#FF79C6',
	success: '#50FA7B',
	warning: '#FFB86C',
	danger: '#FF5555',
	muted: '#6272A4',
	bgDark: '#181824',
	bgCard: '#212230',
	fgLight: '#F8F8F2',
	border: '#44475A',
};

export const THEME = {
	headerBackground: colors.primary,
	headerForeground: colors.fgLight,
	badgeBackground: colors.secondary,
	badgeForeground: colors.bgDark,
	sidebarBorder: colors.border,
	sidebarBorderActive: colors.primary,
	mainBorder: colors.border,
	mainBorderActive: colors.secondary,
	itemForeground: colors.fgLight,
	itemActiveForeground: colors.bgDark,
	itemActiveBackground: colors.primary,
	fgLight: colors.fgLight,
	border: colors.border,
	muted: colors.muted,
	statusBackground: colors.bgCard,
	statusForeground: colors.fgLight,
	statusKey: colors.secondary,
	dialogBackground: colors.bgCard,
	dialogBorder: colors.primary,
	success: colors.success,
	danger: colors.danger,
	bgDark: colors.bgDark,
};